import type { ShellSessionState } from "./types";

export const NLI_COMMANDS = [
  "?", "help", "login", "newuser", "clear", "date", "echo", "finger",
  "hosts", "joke", "phonebook", "coupler", "switchboard", "operator", "dial", "hunt", "pad", "x25", "telex", "telnet", "ssh", "rlogin", "ftp", "gopher", "news",
  "mail", "irc", "relay", "talk", "game", "history", "today", "uptime", "users",
  "who", "qotd", "zcode", "weather", "zork", "clock", "ddate", "when",
  "ipaddr", "mac", "md5", "rand", "roll", "rot13", "uuplot",
  "basic", "calc", "factor", "primes", "ping", "pong", "morse", "cowsay", "figlet",
  "privacy", "rfc", "notes", "bookmark", "bookmarks", "task", "tasks", "taskmgr", "scheduler", "schtasks", "events", "eventvwr", "eventviewer", "eventvwr.msc", "logs", "search", "find", "srchui", "connections", "ncpa.cpl", "netconnections", "netsetup", "netsetup.cpl", "netdiag", "diagnose", "mapdrive", "net", "offline", "sync", "mobsync", "mobsync.exe", "syncmgr", "remote", "mstsc", "mstsc.exe", "tsclient", "runbox", "start", "explorer", "cmd", "cmd.exe", "command.com", "runas", "credentials", "creds", "keymgr", "keymgr.dll", "controlkeymgr", "support", "helpctr", "helpctr.exe", "files", "mailbox", "boards", "system", "sysdm", "winver", "control", "cpl", "accounts", "nusrmgr.cpl", "datetime", "timedate.cpl", "display", "desk.cpl", "sounds", "mmsys.cpl", "power", "powercfg.cpl", "mouse", "main.cpl", "keyboard", "kbd.cpl", "accessibility", "access.cpl", "regional", "intl.cpl", "modems", "telephon.cpl", "odbc", "odbcad32", "programs", "appwiz.cpl", "internet", "inetcpl", "firewall", "firewall.cpl", "updates", "wuaucpl.cpl", "windowsupdate", "performance", "perfmon", "perfmon.msc", "restore", "rstrui", "rstrui.exe", "computer", "compmgmt", "compmgmt.msc", "disk", "diskmgmt", "diskmgmt.msc", "folders", "folderopts", "network", "dialup", "lineage", "era", "devices", "devmgmt", "nodes", "security", "services", "shares", "printers", "printq", "registry", "reg", "units",
  "2048", "aquarium", "rain", "starwars", "eliza", "phoon", "pig", "fnord", "qr",
  "a2", "ac", "advent", "bf", "c8", "cal", "ching", "geoip", "octopus",
  "rig", "sleep", "typespeed", "theme", "desktop",
];

export const LOGGED_IN_COMMANDS = [
  ...NLI_COMMANDS,
  "cat", "cd", "dir", "ls", "netstat", "pwd", "send", "uupath", "uumap",
  "write", "append", "rm", "cp", "mv",
  "wardial", "porthack", "scores", "rootkit", "bbs", "call", "usenet",
  "games", "zc", "zrun", "inbox", "alias", "ver", "status", "whoami",
  "motd", "inventory", "look", "scan", "inspect", "grep", "find", "trace",
  "traceroute", "back", "logout", "save", "load", "solve", "secure", "run",
  "takeover", "owned", "link", "unlink", "camp", "tunnel", "ps", "kill", "glitch",
  "set",
];

export const BADGE_GATES: Record<string, string> = {
  netstat: "networker",
  porthack: "hacker",
  wardial: "wardialer",
  rootkit: "rootkit",
};

export const COMMAND_HELP: Record<string, string> = {
  "?": "Show the command list.",
  help: "Show one-line help or the full command list.",
  login: "Log into an existing account.",
  newuser: "Create a new account.",
  hosts: "Show the visible host graph.",
  phonebook: "Show and edit discovered phone numbers, line types, protocol hints, notes, and dial commands.",
  coupler: "Attach or detach an acoustic coupler before low-speed pre-dial-up dialing.",
  switchboard: "Request a manual route card before opening a long-distance circuit.",
  operator: "Request a long-distance circuit before dialing multi-hop phonebook routes.",
  netstat: "Show your current host access map.",
  finger: "Show user details or remote occupants with finger @host.",
  who: "List active sessions.",
  telnet: "Connect to a host over the shell stack.",
  dial: "Dial a discovered phone number or host through the acoustic-coupler/modem loop.",
  hunt: "Search alternate numbers on a host and select the first reachable line.",
  pad: "Open an X.25 PAD-style packet circuit to a visible multi-hop host.",
  x25: "Alias for PAD packet-switch access.",
  telex: "Open a packet-switched teleprinter circuit to a visible host.",
  ssh: "Connect to a host over the shell stack.",
  rlogin: "Connect to a host over the shell stack.",
  ftp: "Enter FTP mode on a host.",
  gopher: "Enter Gopher mode on a host.",
  news: "Enter the USENET archive transport.",
  mail: "Enter mail mode on a host.",
  irc: "Enter the IRC relay.",
  relay: "Enter the live relay channel surface.",
  talk: "Open a direct talk session with an active user tty.",
  game: "Browse or launch the adventure shelf.",
  wardial: "Scan neighboring hosts and unlock the wardialer badge.",
  porthack: "Create a login on an adjacent host.",
  rootkit: "Take root on a host if you have a kit loaded.",
  bbs: "Enter a host BBS.",
  usenet: "Enter the USENET archive reader.",
  games: "Show the available Z-code shelf.",
  desktop: "Show or switch the active desktop app.",
  set: "Set session options like SSH key material.",
  theme: "Set or show the desktop theme.",
  bookmark: "Save or remove host and route bookmarks.",
  bookmarks: "List saved host and route bookmarks.",
  task: "Queue, list, complete, or clear desktop tasks.",
  tasks: "List queued desktop tasks.",
  taskmgr: "Show backend-derived Task Manager process rows.",
  scheduler: "Show backend-derived Scheduled Tasks rows.",
  schtasks: "Alias for scheduler.",
  events: "Show the server-owned desktop event list.",
  eventvwr: "Alias for events.",
  eventviewer: "Show backend-derived Event Viewer rows.",
  "eventvwr.msc": "Alias for eventviewer.",
  logs: "Alias for events.",
  search: "Search backend-visible workstation artifacts.",
  find: "Alias for search.",
  srchui: "Alias for search.",
  connections: "Show backend-derived Network Connections rows.",
  "ncpa.cpl": "Alias for connections.",
  netconnections: "Alias for connections.",
  netsetup: "Show backend-derived Network Setup Wizard rows.",
  "netsetup.cpl": "Alias for netsetup.",
  netdiag: "Show backend-derived Network Diagnostics rows.",
  diagnose: "Alias for netdiag.",
  mapdrive: "Show backend-derived Map Network Drive rows.",
  net: "Use net use [search] for backend-derived mapped drive rows.",
  offline: "Show backend-derived Offline Files cache and sync rows.",
  sync: "Alias for offline.",
  mobsync: "Alias for offline.",
  "mobsync.exe": "Alias for offline.",
  syncmgr: "Alias for offline.",
  remote: "Show backend-derived Remote Desktop Connection rows.",
  mstsc: "Alias for remote.",
  "mstsc.exe": "Alias for remote.",
  tsclient: "Alias for remote.",
  runbox: "Show backend-derived Run dialog rows without launching real OS processes.",
  start: "Show backend-derived Run dialog rows.",
  explorer: "Show backend-derived Explorer/Run targets.",
  cmd: "Show backend-derived command prompt Run target.",
  "cmd.exe": "Show backend-derived command prompt Run target.",
  "command.com": "Show backend-derived legacy command interpreter Run target.",
  runas: "Show backend-derived elevated Run targets without escalating real privileges.",
  credentials: "Show backend-derived Stored User Names and Passwords rows without revealing secrets.",
  creds: "Alias for credentials.",
  keymgr: "Alias for credentials.",
  "keymgr.dll": "Alias for credentials.",
  controlkeymgr: "Alias for credentials.",
  support: "Show backend-derived Help and Support Center rows.",
  helpctr: "Alias for support.",
  "helpctr.exe": "Alias for support.",
  files: "Show visible files for the current desktop context.",
  mailbox: "Show message summaries for the desktop mail view.",
  boards: "Show BBS and USENET summaries for the desktop boards view.",
  system: "Show backend-derived System Properties rows.",
  sysdm: "Alias for system.",
  winver: "Show the current shell era and system identity.",
  control: "Show backend-derived Control Panel applets.",
  cpl: "Alias for control.",
  accounts: "Show backend-derived User Accounts rows.",
  "nusrmgr.cpl": "Alias for accounts.",
  datetime: "Show backend-derived Date/Time Properties rows.",
  "timedate.cpl": "Alias for datetime.",
  display: "Show backend-derived Display Properties rows.",
  "desk.cpl": "Alias for display.",
  sounds: "Show backend-derived Sounds and Audio Devices rows.",
  "mmsys.cpl": "Alias for sounds.",
  power: "Show backend-derived Power Options rows.",
  "powercfg.cpl": "Alias for power.",
  mouse: "Show backend-derived Mouse Properties rows.",
  "main.cpl": "Alias for mouse.",
  keyboard: "Show backend-derived Keyboard Properties rows.",
  "kbd.cpl": "Alias for keyboard.",
  accessibility: "Show backend-derived Accessibility Options rows.",
  "access.cpl": "Alias for accessibility.",
  regional: "Show backend-derived Regional and Language Options rows.",
  "intl.cpl": "Alias for regional.",
  modems: "Show backend-derived Phone and Modem Options rows.",
  "telephon.cpl": "Alias for modems.",
  odbc: "Show backend-derived ODBC Data Source Administrator rows.",
  odbcad32: "Alias for odbc.",
  programs: "Show backend-derived Add/Remove Programs rows.",
  "appwiz.cpl": "Alias for programs.",
  internet: "Show backend-derived Internet Options rows.",
  inetcpl: "Alias for internet.",
  firewall: "Show backend-derived Windows Firewall rows.",
  "firewall.cpl": "Alias for firewall.",
  updates: "Show backend-derived Automatic Updates rows.",
  "wuaucpl.cpl": "Alias for updates.",
  windowsupdate: "Alias for updates.",
  performance: "Show backend-derived Performance Monitor counters.",
  perfmon: "Alias for performance.",
  "perfmon.msc": "Alias for performance.",
  restore: "Show backend-derived System Restore checkpoints.",
  rstrui: "Alias for restore.",
  "rstrui.exe": "Alias for restore.",
  computer: "Show backend-derived Computer Management rows.",
  compmgmt: "Alias for computer.",
  "compmgmt.msc": "Alias for computer.",
  disk: "Show backend-derived Disk Management rows.",
  diskmgmt: "Alias for disk.",
  "diskmgmt.msc": "Alias for disk.",
  folders: "Show backend-derived Folder Options rows.",
  folderopts: "Alias for folders.",
  network: "Show reachable and remembered hosts for Network Places.",
  dialup: "Show backend-derived Dial-Up Networking entries and phone numbers.",
  lineage: "Show connection-era rows from acoustic couplers through dial-up, UUCP, telnet, and LAN control panels.",
  era: "Alias for lineage.",
  devices: "Show backend-derived Device Manager entries.",
  devmgmt: "Alias for devices.",
  nodes: "Show current, home, and owned systems for My Nodes.",
  security: "Show backend-derived host posture for Security Center.",
  services: "Show backend-derived service rows for visible systems.",
  shares: "Show backend-derived shared folders for Network Neighborhood.",
  printers: "Show backend-derived printer queues and held jobs.",
  printq: "Alias for printers.",
  registry: "Show backend-derived registry-style shell keys.",
  reg: "Alias for registry; use reg query [search].",
  stty: "Change terminal output mode.",
  save: "Save a named shell checkpoint.",
  load: "Load a named shell checkpoint.",
  link: "Mirror another tty session.",
  camp: "Mark a host as camped.",
  tunnel: "Track a direct tunnel route.",
  secure: "Try to seize root on the current host.",
  takeover: "Alias for secure.",
  owned: "Show hosts you control.",
  trace: "Show the UUCP route to a host hop by hop.",
  traceroute: "Alias for trace.",
  solve: "Submit a clue to unlock the archive puzzle layer.",
  run: "Launch a Z-code game.",
  zork: "Launch Zork from the game shelf.",
  advent: "Launch Adventure from the game shelf.",
  zc: "Alias for Z-code launch.",
  zrun: "Alias for Z-code launch.",
  zcode: "Alias for Z-code launch.",
  basic: "Enter TeleBASIC.",
  call: "Enter the monitor on -151.",
  quit: "Leave the current subsystem or shell.",
  exit: "Leave the current subsystem or shell.",
  logout: "Log out of the shell.",
};

export function describeCommand(cmd: string): string {
  return COMMAND_HELP[cmd.toLowerCase()] ?? `${cmd}: see Cyberscape manual`;
}

export function commandsForState(state: ShellSessionState): string[] {
  const base = state.loggedIn ? LOGGED_IN_COMMANDS : NLI_COMMANDS;
  return base.filter((cmd) => {
    const badge = BADGE_GATES[cmd];
    return !badge || state.badges.includes(badge);
  });
}

export function formatCommandList(state: ShellSessionState): string[] {
  const cmds = commandsForState(state);
  const lines: string[] = ["Command, one of the following:"];
  let row = "  ";
  for (const c of cmds) {
    if (row.length + c.length + 3 > 72) {
      lines.push(row);
      row = "  ";
    }
    row += c.padEnd(12);
  }
  if (row.trim()) lines.push(row);
  return lines;
}
