#!/usr/bin/env npx tsx
/**
 * Sync dev-only BBS text corpus into packages/cyberscape for client-side shell.
 * Usage: npx tsx scripts/sync-bbs-corpus.ts
 */
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC_DIR = path.join(ROOT, "data/archives/bbs/textfiles");
const DEST_DIR = path.join(ROOT, "packages/cyberscape/src/data/bbs-corpus");
const INDEX_PATH = path.join(DEST_DIR, "corpus-index.json");
const DATA_PATH = path.join(DEST_DIR, "corpus-data.ts");

interface CorpusEntry {
  id: string;
  filename: string;
  sha256: string;
  bytes: number;
  license_class: "dev-only";
  assignable_tags: string[];
}

function escapeTsString(s: string): string {
  return JSON.stringify(s);
}

async function main(): Promise<void> {
  await mkdir(DEST_DIR, { recursive: true });

  let files: string[];
  try {
    files = (await readdir(SRC_DIR)).filter((f) => /\.(txt|TXT)$/i.test(f));
  } catch {
    console.error(`No corpus source at ${SRC_DIR}`);
    process.exit(1);
  }

  if (!files.length) {
    console.error("No .txt files in corpus source directory");
    process.exit(1);
  }

  const entries: CorpusEntry[] = [];
  const contentMap: Record<string, string> = {};

  for (const filename of files.sort()) {
    const src = path.join(SRC_DIR, filename);
    const buf = await readFile(src);
    const sha256 = createHash("sha256").update(buf).digest("hex");
    const id = filename.replace(/\.(txt|TXT)$/i, "").toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const content = buf.toString("utf8");

    const destCopy = path.join(DEST_DIR, filename);
    await writeFile(destCopy, buf);

    entries.push({
      id,
      filename,
      sha256,
      bytes: buf.length,
      license_class: "dev-only",
      assignable_tags: ["bbs", "textfiles", "1980s"],
    });
    contentMap[id] = content;
    console.log(`[sync] ${filename} sha256=${sha256.slice(0, 12)}… (${buf.length} bytes)`);
  }

  const index = {
    version: 1,
    updated: new Date().toISOString().slice(0, 10),
    source_dir: "data/archives/bbs/textfiles",
    entries,
  };
  await writeFile(INDEX_PATH, `${JSON.stringify(index, null, 2)}\n`);

  const tsLines = [
    "// Generated by scripts/sync-bbs-corpus.ts — do not edit by hand",
    "",
    "export interface CorpusFileRecord {",
    "  id: string;",
    "  filename: string;",
    "  sha256: string;",
    "  bytes: number;",
    "  license_class: \"dev-only\";",
    "  assignable_tags: string[];",
    "  content: string;",
    "}",
    "",
    "export const BBS_CORPUS: CorpusFileRecord[] = [",
    ...entries.map((e) => {
      return `  {
    id: ${escapeTsString(e.id)},
    filename: ${escapeTsString(e.filename)},
    sha256: ${escapeTsString(e.sha256)},
    bytes: ${e.bytes},
    license_class: "dev-only",
    assignable_tags: ${JSON.stringify(e.assignable_tags)},
    content: ${escapeTsString(contentMap[e.id]!)},
  },`;
    }),
    "];",
    "",
  ];
  await writeFile(DATA_PATH, tsLines.join("\n"));
  console.log(`Wrote ${entries.length} files -> ${DEST_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
